### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by koreem** [spencerlambert/mysql-events#20]
I'm getting the following error when I execute the example from the Quick Start:

................/node_modules/mysql-events/index.js:20
                        newInst.child.on('child', child => newInst.emit('child
                                                                            
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.............../client.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

Am I doing something wrong here?

**Comment by spencerlambert** [comment]
Use a node version that supports ES6 or use the older version of mysql-events.
