### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by bgobi1991** [spencerlambert/mysql-events#6]
Hi Team,

The following bug has been came when update the table data.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (D:\examples\mysqlwatch\node_modules\mysql-events\node_modules\zongji\node_modules\mysql\lib\protocol\Protocol.js:103:13)
    at Socket.<anonymous> (D:\examples\mysqlwatch\node_modules\mysql-events\node_modules\zongji\node_modules\mysql\lib\Connection.js:88:28)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)

**Comment by spencerlambert** [comment]
The zongji package handles the mysql connection and doesn't recover well when the database connection is lost.  We have patched our version of zongji, which recovers after losing the database connection.

https://github.com/spencerlambert/zongji
